spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 001128Laika

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

product:
  service:
    url: http://localhost:8081

security:
  jwt:
    secret: dev-secret-0123456789-abcdefghijklmnopqrstuvwxyz
    access-token-expiration-minutes: 15