name: Docker Compose CI

on:
  push:
    branches: [ aws-deployment ]
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      ORDER_SERVICE_CLIENT_SECRET: ${{ secrets.ORDER_SERVICE_CLIENT_SECRET }}

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Enable cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create JWT secret files
      - name: Create JWT public key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > secrets/jwt-public.key

      - name: Create JWT private key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > secrets/jwt-private.key

      # Build and push multi-arch images using docker-compose.yml
      - name: Build and push multi-arch images
        uses: docker/bake-action@v6
        with:
          push: true
          files: docker-compose.yml
          set: |
            *.platform=linux/amd64
        #,linux/arm64

      #- name: Start services
       # run: docker compose up -d

      #- name: Show MySQL logs
      #  if: failure()
      #  run: docker logs order-management-system-mysql-1

      #- name: Show running containers
       # run: docker ps
