name: Docker Compose CI

on:
  push:
    branches: [ cicd ]
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      ORDER_SERVICE_CLIENT_SECRET: ${{ secrets.ORDER_SERVICE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      #- run: |
      #   echo "MYSQL_ROOT_PASSWORD length: ${#MYSQL_ROOT_PASSWORD}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create JWT public key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > secrets/jwt-public.key

      - name: Create JWT private key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > secrets/jwt-private.key

      - name: Build images
        run: docker compose build

      - name: Push images
        run: docker compose push

      - name: Start services
        run: docker compose up -d

      #- name: Show MySQL logs
      #  if: failure()
      #  run: docker logs order-management-system-mysql-1

      - name: Show running containers
        run: docker ps
